name: Build Restaurant POS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Node and npm
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: restaurant-pos-web-build
          path: dist/
